set shell := ["bash", "-eu", "-o", "pipefail", "-c"]

machine-port := `jq -r '.server.port' config.json`
machine-url := "http://localhost:" + machine-port

# List available recipes
default:
    @just --list

# Remove build artifacts
clean:
    rm -rf build

# Build binary artifacts
build:
    just build-machine

# Build and run coffee machine
run:
    just build-machine
    ./build/bin/machine --port={{machine-port}}

# Get coffee machine status
status:
    @curl -s {{machine-url}}/status | jq

# Submit coffee order
[arg("type", help="coffee type")]
order type:
    @curl \
        -s \
        -o /dev/null \
        -w "HTTP %{http_code}\n" \
        -X POST \
        -H "Content-Type: application/json" \
        -d '{"type":"{{type}}"}' \
        {{machine-url}}/order

# Get brewing progress
progress:
    @curl -s {{machine-url}}/progress | jq

# Watch brewing progress until complete
watch-progress:
    @watch -n 1 "curl -s {{machine-url}}/progress | jq"

[private]
build-machine:
    @mkdir -p build/bin
    go build -o build/bin/machine ./cmd/machine
