set shell := ["bash", "-eu", "-o", "pipefail", "-c"]

import 'just/api.just'
import 'just/docker.just'

backend-url := "http://localhost:8081"

# List available recipes
default:
    @just --list

# Execute gradle wrapper command
gradlew *args:
    @./gradlew {{args}}
