set shell := ["bash", "-eu", "-o", "pipefail", "-c"]

import 'just/machine.just'
import 'just/docker.just'
import 'just/api.just'

machine-url := "http://localhost:8082"

# List available recipes
default:
    @just --list
