spring.main.banner-mode=off
spring.jpa.open-in-view=false

spring.datasource.url=jdbc:tc:postgresql:16-alpine:///coffee_backend
spring.datasource.hikari.maximum-pool-size=2

springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

coffee.machine.connect-timeout=100ms
coffee.machine.read-timeout=100ms
