name: CI

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/**"
      - "docker-compose.yml"
      - "backend/build.gradle"
      - "backend/settings.gradle"
      - "backend/gradlew"
      - "backend/gradlew.bat"
      - "backend/gradle/**"
      - "backend/compose.yml"
      - "backend/src/**"
      - "machine/go.mod"
      - "machine/Dockerfile"
      - "machine/compose.yml"
      - "machine/cmd/**"
      - "machine/internal/**"
      - "!**/*.md"

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    env:
      DB_HOST: localhost
      DB_NAME: coffee
      DB_USER: coffee
      DB_PASSWORD: coffee

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install just
        uses: extractions/setup-just@v4

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: machine/go.mod
          cache-dependency-path: machine/go.mod

      - name: Build machine
        run: just machine::build

      - name: Run machine tests with coverage
        run: just machine::test-coverage

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-read-only: false
          cache-cleanup: never

      - name: Build backend
        run: just backend::gradlew assemble

      - name: Run backend tests with coverage
        run: just backend::gradlew test jacocoTestReport

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: machine/build/coverage/coverage.out, backend/build/reports/jacoco/test/jacocoTestReport.xml
          disable_search: true
          fail_ci_if_error: true
